"""initial

Revision ID: 2ee52a3a89e6
Revises: 
Create Date: 2023-04-21 22:29:49.594930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee52a3a89e6'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacja', sa.String(length=50), nullable=False),
    sa.Column('nazwa', sa.String(length=50), nullable=False),
    sa.Column('sztuk', sa.Integer(), nullable=False),
    sa.Column('cena', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    op.create_table('produkt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=50), nullable=False),
    sa.Column('sztuk', sa.Integer(), nullable=False),
    sa.Column('cena', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    op.create_table('saldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldo')
    op.drop_table('produkt')
    op.drop_table('historia')
    # ### end Alembic commands ###
